### ISSUE TITLE
'Missing access token parameter.' when running authorize

### ISSUE THREAD

**Issue by vadi2** [joar/automgtic#1]
Was running --authorize, gave it the code and it crashed with: 

`Traceback (most recent call last):
  File "./run.py", line 39, in <module>
    automgtic.authorize()
  File "/home/vadi/Programs/automgtic/automgtic/__init__.py", line 146, in authorize
    token_data = client.parse_request_body_response(token_response)
  File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/__init__.py", line 302, in parse_request_body_response
    response = parse_token_response(body, scope=scope)
  File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/parameters.py", line 251, in parse_token_response
    validate_token_parameters(params, scope)
  File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/parameters.py", line 259, in validate_token_parameters
    raise KeyError("Missing access token parameter.")
KeyError: 'Missing access token parameter.'`

**Comment by joar** [comment]
i think this was a GNU MediaGoblin bug. Shiuld be fixed now. Update your GNU MediaGoblin instance and try again.

**Comment by vadi2** [comment]
I updated and it happened again.

```
  Traceback (most recent call last):
    File "./run.py", line 39, in <module>
      automgtic.authorize()
    File "/home/vadi/Programs/automgtic/automgtic/__init__.py", line 146, in authorize
      token_data = client.parse_request_body_response(token_response)
    File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/__init__.py", line 302, in parse_request_body_response
      response = parse_token_response(body, scope=scope)
    File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/parameters.py", line 251, in parse_token_response
      validate_token_parameters(params, scope)
    File "/home/vadi/Programs/automgtic/local/lib/python2.7/site-packages/oauthlib/oauth2/draft25/parameters.py", line 259, in validate_token_parameters
      raise KeyError("Missing access token parameter.")
  KeyError: 'Missing access token parameter.'
```

**Comment by joar** [comment]
Check your GMG logs for an `/oauth/access_token` request and if the request
causes an exception in GMG.

**Comment by vadi2** [comment]
I'm afraid I don't know what a GMG log is.

**Comment by joar** [comment]
@vadi2 By `GMG log` I mean the output of e.g. the `./lazyserver.sh` or `paster` command you are running.

**Comment by vadi2** [comment]
It didn't mention anything in regards to this incident:

$ ./lazyserver.sh
Using paster config: paste_local.ini
Using ./bin/paster
- export CELERY_ALWAYS_EAGER=true
- ./bin/paster serve paste_local.ini --reload
  Starting subprocess with file monitor
  2012-10-19 17:17:04,600 INFO    [mediagoblin.app] GNU MediaGoblin 0.3.2.dev
  main server starting
  2012-10-19 17:17:04,604 INFO    [mediagoblin.app] Setting up plugins.
  2012-10-19 17:17:04,604 INFO    [mediagoblin.init.plugins] Importing plugin
  module: mediagoblin.plugins.oauth
  2012-10-19 17:17:04,625 INFO    [mediagoblin.plugins.oauth] Setting up
  OAuth...
  Starting server in PID 16667.
  serving on http://127.0.0.1:6543
  ^C^C caught in monitor process

**Comment by setheus** [comment]
I believe I'm having the same issue. Tried to look more into it and found:

(Pdb) print token_response
{"error_description": "Missing client_secret in request", "error": "invalid_request"}

**Comment by joar** [comment]
Thank you for the digging!

It seems that you might have registered the OAuth client as
"confidential" while it should be registered as "public" :)

On 10/24/2012 08:35 PM, setheus wrote:

> I believe I'm having the same issue. Tried to look more into it and found:
> 
> (Pdb) print token_response
> {"error_description": "Missing client_secret in request", "error":
> "invalid_request"}
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jwandborg/automgtic/issues/1#issuecomment-9750937.

## 

http://wandborg.se
http://talka.tv

**Comment by vadi2** [comment]
I've been registering mine public, so I think an issue is still there.

**Comment by joar** [comment]
Yes. I agree with you on that point.

**Comment by joar** [comment]
I haven't had the time to fix this yet, just letting you know.

**Comment by joar** [comment]
I can not reproduce this issue, as long as I register the client as public (and **delete** the old access_token entry in `automgtic_local.ini`, if I'm in a 'failed' environment).
