### ISSUE TITLE
oauthlib install requirement missing

### ISSUE THREAD

**Issue by msjoberg** [joar/automgtic#2]
```
$ python -c "from automgtic.models import Base, engine 
> Base.metadata.create_all(engine)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "automgtic/__init__.py", line 10, in <module>
    from oauthlib.oauth2.draft25 import WebApplicationClient
ImportError: cannot import name WebApplicationClient
```

After this change seems to work fine:

```
diff --git a/setup.py b/setup.py
index 6c59f14..6a97c2b 100644
--- a/setup.py
+++ b/setup.py
@@ -13,5 +13,6 @@ setup(
             'configobj',
             'sqlalchemy',
             'simplejson',
-            'poster'],
+            'poster',
+            'oauthlib'],
         license='Apache License v2')
```

**Comment by joar** [comment]
Thank you! Fixed in e25a18c0939c69135948fe619ec692659c792995
